import { mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { buildRegistry, identifier, writeRegistry } from "./generate.mjs";

let root: string;
const touch = (rel: string, content = "export {};\n") => {
  mkdirSync(dirname(join(root, rel)), { recursive: true });
  writeFileSync(join(root, rel), content);
};
beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "registry-gen-"));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

const HEADER = "// GENERATED by tools/registry-gen. Do not edit: `pnpm install` rewrites it.\n";

describe("buildRegistry", () => {
  it("writes empty registries when there are no features or platform modules", () => {
    const files = buildRegistry(root);
    expect(Object.keys(files).sort()).toEqual([
      "features/_registry/client.ts",
      "features/_registry/manifests.ts",
      "features/_registry/mobile.ts",
      "features/_registry/server.ts",
      "features/_registry/web.ts",
      "platform/_registry/server.ts",
    ]);
    expect(files["features/_registry/manifests.ts"]).toBe(`${HEADER}\nexport const manifests = [] as const;\n`);
    expect(files["features/_registry/web.ts"]).toBe(`${HEADER}\nexport const webParts = {\n} as const;\n`);
  });

  it("imports each feature's manifest and only the parts it has, in name order", () => {
    touch("features/packing-list/manifest.ts");
    touch("features/packing-list/mobile/index.ts");
    touch("features/money/manifest.ts");
    touch("features/money/server/index.ts");
    touch("features/money/web/index.ts");
    const files = buildRegistry(root);
    expect(files["features/_registry/manifests.ts"]).toBe(
      `${HEADER}import money from '../money/manifest';\nimport packingList from '../packing-list/manifest';\n\nexport const manifests = [money, packingList] as const;\n`,
    );
    expect(files["features/_registry/server.ts"]).toBe(
      `${HEADER}import * as money from '../money/server/index';\n\nexport const serverParts = {\n  'money': money,\n} as const;\n`,
    );
    expect(files["features/_registry/mobile.ts"]).toBe(
      `${HEADER}import * as packingList from '../packing-list/mobile/index';\n\nexport const mobileParts = {\n  'packing-list': packingList,\n} as const;\n`,
    );
    expect(files["features/_registry/client.ts"]).toBe(`${HEADER}\nexport const clientParts = {\n} as const;\n`);
  });

  it("registers platform modules' server parts", () => {
    touch("platform/sync/server/index.ts");
    touch("platform/identity/core/index.ts");
    expect(buildRegistry(root)["platform/_registry/server.ts"]).toBe(
      `${HEADER}import * as sync from '../sync/server/index';\n\nexport const serverParts = {\n  'sync': sync,\n} as const;\n`,
    );
  });

  it("skips _registry, _template, dot-folders and node_modules", () => {
    touch("features/_template/manifest.ts");
    touch("features/_registry/manifests.ts");
    touch("features/.cache/manifest.ts");
    touch("features/node_modules/x/manifest.ts");
    expect(buildRegistry(root)["features/_registry/manifests.ts"]).toBe(`${HEADER}\nexport const manifests = [] as const;\n`);
  });

  it("refuses a feature folder without a manifest", () => {
    touch("features/money/server/index.ts");
    expect(() => buildRegistry(root)).toThrow("features/money has no manifest.ts");
  });

  it("refuses a module name that cannot become an import", () => {
    touch("features/Money/manifest.ts");
    expect(() => buildRegistry(root)).toThrow('"Money" is not a valid module name');
  });

  it("refuses a name with a trailing dash", () => {
    touch("features/money-/manifest.ts");
    expect(() => buildRegistry(root)).toThrow('"money-" is not a valid module name');
  });

  it("refuses a name with a doubled dash", () => {
    touch("features/a--b/manifest.ts");
    expect(() => buildRegistry(root)).toThrow('"a--b" is not a valid module name');
  });

  it("refuses a name that becomes a reserved word", () => {
    touch("features/package/manifest.ts");
    expect(() => buildRegistry(root)).toThrow('"package" becomes the reserved word package');
  });

  it("refuses two names that become the same identifier", () => {
    touch("features/v-2/manifest.ts");
    touch("features/v2/manifest.ts");
    expect(() => buildRegistry(root)).toThrow('"v-2" and "v2" both become the identifier v2');
  });
});

describe("writeRegistry", () => {
  it("writes every file once, then leaves unchanged files untouched", () => {
    touch("features/money/manifest.ts");
    const first = writeRegistry(root);
    expect(first.written).toHaveLength(6);
    const manifests = join(root, "features/_registry/manifests.ts");
    const before = statSync(manifests).mtimeMs;
    const second = writeRegistry(root);
    expect(second.written).toEqual([]);
    expect(second.unchanged).toHaveLength(6);
    expect(statSync(manifests).mtimeMs).toBe(before);
    expect(readFileSync(manifests, "utf8")).toContain("import money from '../money/manifest';");
  });
});

describe("identifier", () => {
  it.each([
    ["money", "money"],
    ["packing-list", "packingList"],
    ["x-2-y", "x2Y"],
  ])("%s → %s", (name, id) => {
    expect(identifier(name)).toBe(id);
  });
});
