/**
 * The registry generator (spec §0 "Registry"). Metro cannot run import.meta.glob,
 * so the list of features is written out as plain imports that both apps (the
 * composition roots) read. The output is gitignored and rebuilt on every install,
 * so parallel branches never conflict on it.
 *
 * Node built-ins only: this runs in postinstall on this machine, in CI, on Vercel
 * and on EAS, before any dependency is guaranteed to be usable.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** The parts a feature can contribute, each through `<part>/index.ts`. */
export const FEATURE_PARTS = ['client', 'server', 'web', 'mobile'];
/** Platform modules register only their server part (commands and pulls). */
export const PLATFORM_PARTS = ['server'];
const NAME = /^[a-z][a-z0-9-]*$/;
const HEADER = '// GENERATED by tools/registry-gen. Do not edit: `pnpm install` rewrites it.\n';

/**
 * Every generated file, as repo-relative path → content. Pure: reads the tree, writes nothing.
 * @param {string} root absolute repo root
 * @returns {Record<string, string>}
 */
export function buildRegistry(root) {
  const features = listModules(join(root, 'features'));
  for (const name of features) {
    if (!existsSync(join(root, 'features', name, 'manifest.ts'))) {
      throw new Error(`features/${name} has no manifest.ts — every feature folder needs one (copy features/_template)`);
    }
  }
  const platform = listModules(join(root, 'platform'));

  /** @type {Record<string, string>} */
  const files = {};
  files['features/_registry/manifests.ts'] = listFile(features.map((name) => ({ name, from: `../${name}/manifest` })));
  for (const part of FEATURE_PARTS) {
    const present = features.filter((name) => existsSync(join(root, 'features', name, part, 'index.ts')));
    files[`features/_registry/${part}.ts`] = mapFile(present.map((name) => ({ name, from: `../${name}/${part}/index` })), part);
  }
  for (const part of PLATFORM_PARTS) {
    const present = platform.filter((name) => existsSync(join(root, 'platform', name, part, 'index.ts')));
    files[`platform/_registry/${part}.ts`] = mapFile(present.map((name) => ({ name, from: `../${name}/${part}/index` })), part);
  }
  return files;
}

/**
 * Write the registry, touching only files whose content changed (so watchers stay quiet).
 * @param {string} root absolute repo root
 * @returns {{ written: string[], unchanged: string[] }}
 */
export function writeRegistry(root) {
  const written = [];
  const unchanged = [];
  for (const [rel, content] of Object.entries(buildRegistry(root))) {
    const path = join(root, rel);
    if (existsSync(path) && readFileSync(path, 'utf8') === content) {
      unchanged.push(rel);
      continue;
    }
    mkdirSync(join(path, '..'), { recursive: true });
    writeFileSync(path, content);
    written.push(rel);
  }
  return { written, unchanged };
}

/** @typedef {{ name: string, from: string }} Entry */

/**
 * Module folders under a layer, sorted; `_registry`, `_template` and dot-folders are not modules.
 * @param {string} dir
 * @returns {string[]}
 */
function listModules(dir) {
  if (!existsSync(dir)) return [];
  const names = readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('_') && !entry.name.startsWith('.') && entry.name !== 'node_modules')
    .map((entry) => entry.name)
    .sort();
  for (const name of names) {
    if (!NAME.test(name)) throw new Error(`"${name}" is not a valid module name: use lowercase letters, digits and dashes`);
  }
  return names;
}

/**
 * "packing-list" → "packingList": a safe identifier for a module name that passed NAME.
 * @param {string} name
 * @returns {string}
 */
export function identifier(name) {
  return name.replace(/-([a-z0-9])/g, (_match, /** @type {string} */ c) => c.toUpperCase());
}

/**
 * @param {Entry[]} entries
 * @returns {string}
 */
function listFile(entries) {
  const imports = entries.map((e) => `import ${identifier(e.name)} from '${e.from}';\n`).join('');
  const list = entries.map((e) => identifier(e.name)).join(', ');
  return `${HEADER}${imports}\nexport const manifests = [${list}] as const;\n`;
}

/**
 * @param {Entry[]} entries
 * @param {string} part
 * @returns {string}
 */
function mapFile(entries, part) {
  const imports = entries.map((e) => `import * as ${identifier(e.name)} from '${e.from}';\n`).join('');
  const body = entries.map((e) => `  '${e.name}': ${identifier(e.name)},\n`).join('');
  return `${HEADER}${imports}\nexport const ${part}Parts = {\n${body}} as const;\n`;
}
